# Generated by Django 4.2.6 on 2023-11-20 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
