# Generated by Django 4.2.6 on 2023-11-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0003_answer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='parent_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='question_api.answer'),
        ),
    ]
