# Generated by Django 4.2.6 on 2023-11-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_api', '0004_answer_parent_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='responding_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question_api.answer'),
        ),
    ]
